# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6386186eb821a22f610ebe7ea517e2f04dfe2253467b162318d0b74298e99bea3c149754fa9f1be68b2b1fb86080f4c1dc3d643e670b584c29a32a90953a2f14

test:
  secret_key_base: fb05330f33b809cee99acd2bb9e0ccd4470b836c80f57bc66587d494b01222e7a7df26a335d9f3e61f954d30d76d5a9208c4b22ce24b0ab2883742d0f47f3115

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
